// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table usuario {
  id integer [primary key]
  num_id integer [unique] 
  nombre varchar
  apellido varchar
  rol integer
  tarjeta_id integer
  created_at timestamp
  updated_at timestamp
}

Table rol {
  id integer [primary key]
  descripcion varchar
}

Table tarjeta {
  id integer [primary key]
  numero varchar
}

Table reserva {
  id integer [primary key]
  id_propiedad integer
  id_inquilino integer
  id_usuario_carga integer
  cantidad_personas integer
  monto_pagado 
  monto_total
  id_chat integer
  id_estado interger 
  fecha_inicio date
  fecha_fin date
  created_at timestamp
  updated_at timestamp
}

Table propiedad {
  id integer [primary key]
  nombre varchar [unique]
  descripcion varchar
  entre_calles varchar
  calle varchar
  numero integer
  piso varchar
  depto varchar
  id_ciudad integer
  huespedes integer
  ambientes integer
  banios integer
  cocheras integer
  precioNoche real
  codigoAcceso varchar
  is_habilitada boolean
  id_pol_reserva integer
  id_tipo integer
  id_ciudad integer
  created_at timestamp
  updated_at timestamp
}

Table provincia {
  id integer [primary key]
  nombre varchar
}
Table ciudad {
  id integer [primary key]
  nombre varchar
  id_provincia integer
}


Table politica_reserva {
  id integer [primary key]
  descripcion varchar
}

Table calificacion_user {
  id integer [primary key]
  evaluado_id integer [not null]   // el usuario que recibe la calificación
  evaluador_id integer [not null]  // el usuario que califica (dueño o inquilino)
  puntaje integer
  comentario text
  created_at timestamp
}

Table calificacion_prop {
  id integer [primary key]
  propiedad_id integer [not null] // FK a propiedad
  usuario_id integer [not null]   // quién califica
  puntaje integer                 // de 1 a 5, por ejemplo
  puntaje integer                 // de 1 a 5, por ejemplo
  puntaje integer                 // de 1 a 5, por ejemplo
  puntaje integer                 // de 1 a 5, por ejemplo
  puntaje integer                 // de 1 a 5, por ejemplo
  comentario text
  created_at timestamp
}

Table chat {
  id integer [primary key]
  mensaje_id integer
  emisor_id integer
  receptor_id integer
}

Table mensaje {
  id integer [primary key]
  chat_id integer [not null]
  emisor_id integer
  receptor_id integer
  hora timestamp
  texto text
}


Table imagen_propiedad {
  id integer [primary key]
  propiedad_id integer [not null]
  url text [note: 'URL de la imagen almacenada']
}

// Relaciones

Ref: usuario.tarjeta_id - tarjeta.id

Ref: reserva.propiedad_id > propiedad.id
Ref: reserva.inquilino_id > usuario.id
Ref: reserva.chat_id > chat.id

Ref: propiedad.id_pol_reserva > politica_reserva.id

Ref: imagen_propiedad.propiedad_id > propiedad.id

Ref: mensaje.chat_id > chat.id
Ref: mensaje.emisor_id > usuario.id
Ref: mensaje.receptor_id > usuario.id

Ref: calificacion_user.evaluado_id - usuario.id
Ref: calificacion_user.evaluador_id - usuario.id

Ref: calificacion_prop.usuario_id > usuario.id
Ref: calificacion_prop.propiedad_id > propiedad.id

Ref: propiedad.id_ciudad > ciudad.id
Ref: usuario.rol > rol.id
Ref: ciudad.id_provincia < provincia.id
